### ISSUE TITLE
deprecate asset_root

### ISSUE THREAD

**Issue by afeld** [18F/pages-server#55]
While `asset_root` support is nice for common scripts being updated across our sites all at once, it has some significant downsides:
- It has caused unexpected breakage many times, since some sites may have an old version of the template(s) via the `guides_style_18f` gem that refer to assets whose path has changed, etc.
- It adds a bit too much magic for my tastes.
- Published sites behave differently from ones run locally.

I would be in favor of #21 instead.
## TODOs
- [ ] Remove `asset_root` support in Pages (_shouldn't_ be a problem, since new builds would just use the styles from the gem rather than a central URL)
- [ ] Remove `asset_root` from [across our various repositories](https://github.com/search?p=2&q=user%3A18f+%28asset_root+OR+assetRoot%29&ref=searchresults&type=Code&utf8=%E2%9C%93)
- [ ] Remove occurrences of [`guides_style_18f_asset_root`](https://github.com/search?utf8=%E2%9C%93&q=user%3A18f+guides_style_18f_asset_root&type=Code&ref=searchresults)
